operations_management_administration: 3.10
insurance: 3.10
annual_leases_fees: 5.96
operating_facilities: 2.38
environmental_health_safety_monitoring: 5.96 #property tax 
onshore_electrical_maintenance: 0
labor: 4.86 # $60,787 per technician, 1 tech per 12.5 MW
